# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_bynder"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_bynder:
    # Applies to all files under models/example/
    base:
      materialized: table
    intermediate:
      materialized: table
    int: # Sacha will change this name
      materialized: view
    temp_sources:
      materialized: table
    dims:
      materialized: table
    facts:
      materialized: table  
      

seeds:
  dbt_bynder:
    sales_budget:
      +column_types:
        budget_date: timestamp_ntz(9)
    budget_create_group_dummy:
      +column_types:
        month: timestamp_ntz(9)
    sales_targets_poc:
      +column_types:
        date: timestamp_ntz(9)
        new_start_dates: timestamp_ntz(9)
    marketing_targets_poc:
      +column_types:
        mql_date: timestamp_ntz(9)
        sql_date: timestamp_ntz(9)
        opp_date: timestamp_ntz(9)
    Forcast_ARR_2:
      +column_types:
        Date: timestamp_ntz(9)
    MDT_initative_3:
      +column_types:
        Date: timestamp_ntz(9)
    mdt_objectives:
      +column_types:
        Date: timestamp_ntz(9)
    mdt_graph:
      +column_types:
        Date: timestamp_ntz(9)
    mdt_graph_2:
      +column_types:
        Date: timestamp_ntz(9)
    MDT_GLOBAL_DATA:
      +column_types:
        Date: timestamp_ntz(9)

snapshots:
  transient: false
